TokTok/hs-github-tools

.gitmodules
.travis.yml
Setup.lhs
pull-status.cabal
src/Main.hs
src/Review.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/pull-status/4)

Use the released github version 0.15.0.

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/pull-status/6)

Add cabal sandbox config to gitignore.

---

Makefile
pull-status.cabal
src/Requests.hs
src/changelog.hs
src/pull-status.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/pull-status/7)

Add initial version of changelog generator.

---

github-tools.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/9)

fix repo name

---

github-tools.cabal
web/TokTok/Hello.hs
web/TokTok/Webhooks.hs
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/12)

Parse github webhooks and log their contents.

---

github-tools.cabal
web/TokTok/Hello.hs
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/16)

Add /hello/changelog method.

---

web/GitHub/Types.hs
web/GitHub/Types/Base.hs
web/GitHub/Types/Event.hs
web/GitHub/Types/Events.hs
web/GitHub/Types/Events/CommitCommentEvent.hs
web/GitHub/Types/Events/CreateEvent.hs
web/GitHub/Types/Events/DeleteEvent.hs
web/GitHub/Types/Events/DeploymentEvent.hs
web/GitHub/Types/Events/DeploymentStatusEvent.hs
web/GitHub/Types/Events/ForkEvent.hs
web/GitHub/Types/Events/GollumEvent.hs
web/GitHub/Types/Events/IssueCommentEvent.hs
web/GitHub/Types/Events/IssuesEvent.hs
web/GitHub/Types/Events/MemberEvent.hs
web/GitHub/Types/Events/MembershipEvent.hs
web/GitHub/Types/Events/MilestoneEvent.hs
web/GitHub/Types/Events/OrganizationEvent.hs
web/GitHub/Types/Events/PingEvent.hs
web/GitHub/Types/Events/PullRequestEvent.hs
web/GitHub/Types/Events/PullRequestReviewCommentEvent.hs
web/GitHub/Types/Events/PullRequestReviewEvent.hs
web/GitHub/Types/Events/PushEvent.hs
web/GitHub/Types/Events/ReleaseEvent.hs
web/GitHub/Types/Events/StatusEvent.hs
web/GitHub/Types/Events/WatchEvent.hs
web/GitHub/Types/PayloadParser.hs
web/TokTok/Webhooks.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/18)

Split off payload parser into its own module.

---

github-tools.cabal
web/GitHub/Types/Base/Deployment.hs
web/GitHub/Types/Events/IssuesEvent.hs
web/TokTok/Hello.hs

We don't know what payload is, but "Value" would always work, so we
wouldn't find out when it turns out to be more than an empty object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/23)

Add data for "labeled" event and fix "payload" field.

---

github-tools.cabal
web/TokTok/Hello.hs

http://git-critique.herokuapp.com/hello/pulls
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/25)

Add /hello/pulls html output for open PRs (hub-pulls).

---

github-tools.cabal
web/GitHub/Types/Base/Repository.hs
web/GitHub/Types/Events.hs
web/GitHub/Types/Events/LabelEvent.hs
web/GitHub/Types/Events/RepositoryEvent.hs
web/GitHub/Types/PayloadParser.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/31)

Add label and repository events.

---

src/Changelogs.hs
src/PullStatus.hs
src/Review.hs
web/GitHub/Types/Base/DateTime.hs
web/GitHub/Types/Base/RepoOwner.hs
web/GitHub/Types/Events/PullRequestEvent.hs
web/GitHub/Types/Events/PullRequestReviewEvent.hs
web/GitHub/Types/PayloadParser.hs
web/GitHub/WebHook/Handler.hs
web/TokTok/Hello.hs
web/TokTok/Webhooks.hs
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/34)

Clean up some hlint warnings.

---

.leaf.yml
.travis.yml
src/PullStatus.hs
templates/base.yml
templates/haskell.yml
tools/expand-yaml
web/TokTok/Hello.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/33)

Add YAML template expansion script and use it for .travis.yml.

---

.travis.yml
tools/expand-yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/41)

Add comment about .travis.yml being generated.

---

.travis.yml
templates/base.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/38)

Only fetch 1 revision from git during Travis builds.

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/49)

Add appveyor configuration.

---

src/GitHub/Types/Base/Repository.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/51)

`$['pull_request'].head.repo.description` can be null.

---

github-tools.cabal
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/53)

Enable CORS on the hello app.

---

tools/hub-roadmap.hs

It displayed the changelog instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/52)

Make the hub-roadmap command actually display the roadmap.

---

reviewable_script.js

This script is used on all repos. If any repos need special treatment,
that needs to be coded in this script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/59)

Reduce reviewers required to 2 for now.

---

reviewable_script.js

This shows something like '1 file needs 2 more reviewers' now. I've also
increased the number of reviewers to 3 again, hoping for community
reviews to take off a bit more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/63)

Add the number of additional reviewers needed to the message.

---

LICENSE.md
github-tools.cabal

Taken from https://www.gnu.org/licenses/agpl-3.0.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/66)

Use official markdown license for AGPLv3.

---

src/Changelogs.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/60)

Use /pull/ for PR links instead of /issues/.

---

src/Changelogs.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/62)

Show backlog items on the roadmap.

---

web/TokTok/Hello.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/69)

Cache roadmap and changelog for 5 minutes instead of forever.

---

web/TokTok/Hello.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/67)

Add an api call to get the source repository link.

---

tools/git-sync

This very script helps rebasing branches. It's just a short cut for
something I need to do very often, so I don't want to spell it out every
time. Usage:
```
$ git sync my-branch
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/65)

Add git-sync tool from toktok-stack.

---

src/Changelogs.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/73)

Display pull requests before issues in the roadmap.

---

reviewable_script.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/68)

Fix pluralisation of "need"/"needs" in reviewable script.

---

.travis.yml
templates/haskell.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/74)

Make diffs after formatting fail the build.

---

github-tools.cabal
web/TokTok/Hello.hs

This is valid in servant 0.5 and required in 0.10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/77)

Use Handler type instead of Server for handlers.

---

github-tools.cabal
src/PullStatus.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/81)

Match StateBlocked in PRs. Require github 0.16.0.

---

src/GitHub/Types/Base/Repository.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/83)

Add has_projects field to Repository.

---

github-tools.cabal
src/GitHub/Types/Base/CommitDetails.hs
src/GitHub/Types/Base/Deployment.hs
src/GitHub/Types/Base/Issue.hs
src/GitHub/Types/Base/IssueComment.hs
src/GitHub/Types/Base/License.hs
src/GitHub/Types/Base/PullRequest.hs
src/GitHub/Types/Base/Repository.hs
src/GitHub/Types/Base/User.hs
src/GitHub/Types/Base/Verification.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/84)

Add "license" and various other new fields.

---

github-tools.cabal
src/GitHub/Types/Base/Deployment.hs
src/GitHub/Types/Base/DeploymentPayload.hs
src/GitHub/Types/Base/License.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/85)

spdx_id and url in license can be null.

---

src/GitHub/Types/Base/PullRequest.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/87)

requested_reviewers is now a list of Users instead of names.

---

src/GitHub/Types/Base/PullRequest.hs
src/GitHub/Types/Events/PullRequestEvent.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/90)

GitHub now supports requesting reviews from teams.

---

BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/94)

Add bazel BUILD config for github-tools.

---

BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/100)

Rename github-tools repo to hs-github-tools.

---

.gitignore
.travis.yml
BUILD.bazel
appveyor.yml
github-tools.cabal
src/Changelogs.hs
src/GitHub/WebHook/Handler.hs
src/PullStatus.hs
src/Requests.hs
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/107)

Use new rules_haskell name for bazel 2.1.1.

---

src/GitHub/Types/Base/ReviewComment.hs
src/GitHub/Types/Events/IssuesEvent.hs
src/GitHub/Types/Events/PullRequestEvent.hs
src/GitHub/Types/Events/PullRequestReviewEvent.hs
tools/git-sync

Also add a git-sync version that syncs master to upstream/master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/115)

Add "milestone" to the "issues" event.

---

src/GitHub/Types/Base/Release.hs
tools/git-submit
tools/git-sync

Also: make git submit/sync work when a branch is already checked out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/117)

Add node_id to release object type.

---

.github/docker/Dockerfile
.github/workflows/publish.yml
.gitignore
BUILD.bazel
src/GitHub/Types/Base/CheckSuite.hs
src/GitHub/Types/Base/Repository.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/132)

chore: Update types to support new fields in the github webhook payloads

---

src/GitHub/Types/Base/Permissions.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/133)

chore: Add new permissions to the data model.

---

.github/docker/Dockerfile
.github/docker/Dockerfile.heroku
.github/settings.yml
Procfile
heroku.yml
src/GitHub/Types/Base/Permissions.hs
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/135)

chore: Add another missing permission to Permissions.

---

heroku.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/136)

chore: Fix heroku dockerfile reference.

---

src/GitHub/Types/Base/Permissions.hs

Will we ever run out?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/138)

chore: Yet more permissions.

---

.github/docker/Dockerfile
.github/docker/Dockerfile.heroku
BUILD.bazel
github-tools.cabal
src/GitHub/Tools/AutoMerge.hs
src/GitHub/Tools/PullRequestInfo.hs
src/GitHub/Tools/PullStatus.hs
tools/BUILD.bazel
tools/hub-automerge.hs
web/TokTok/Handlers.hs
web/TokTok/Webhooks.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/141)

feat: Implement auto-merge feature for toktok repos.

---

.github/docker/Dockerfile.heroku

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/142)

chore: Fix path to webapp in heroku image build.

---

.github/docker/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/146)

chore: Use toktok-stack:haskell for post-merge build.

---

github-tools.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/147)

chore: Allow the next github package version.

---

.github/docker/Dockerfile
github-tools.cabal
src/GitHub/Types/Base.hs
src/GitHub/Types/Base/CheckCommitRef.hs
src/GitHub/Types/Base/CheckCommitRepo.hs
src/GitHub/Types/Base/CheckPullRequest.hs
src/GitHub/Types/Base/CheckRun.hs
src/GitHub/Types/Base/CheckSuite.hs
src/GitHub/Types/Base/DeploymentStatus.hs
src/GitHub/Types/Base/Label.hs
src/GitHub/Types/Base/Repository.hs
src/GitHub/Types/Base/SimpleRepository.hs
src/GitHub/Types/Base/Team.hs
src/GitHub/Types/Base/UserRef.hs
src/GitHub/Types/Base/Workflow.hs
src/GitHub/Types/Base/WorkflowJob.hs
src/GitHub/Types/Base/WorkflowRun.hs
src/GitHub/Types/Base/WorkflowStep.hs
src/GitHub/Types/Events.hs
src/GitHub/Types/Events/PullRequestReviewEvent.hs
src/GitHub/Types/Events/WorkflowJobEvent.hs
src/GitHub/Types/Events/WorkflowRunEvent.hs
src/GitHub/Types/PayloadParser.hs
tools/deploy.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/154)

feat: Add support for workflow events.

---

src/GitHub/Types/Base/Deployment.hs
src/GitHub/Types/Base/Issue.hs
src/GitHub/Types/Base/PullRequest.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/158)

chore: Add production/transient environment fields.

---

src/GitHub/Tools/AutoMerge.hs
src/GitHub/Types/Base/DeploymentStatus.hs
src/GitHub/Types/Base/Milestone.hs
src/GitHub/Types/Base/Release.hs
src/GitHub/Types/Base/StatusCommit.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/159)

chore: Add missing environment_url.

---

github-tools.cabal
src/GitHub/Tools/NetworkGraph.hs
src/GitHub/Types/Base/Issue.hs
web/TokTok/Hello.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/161)

feat: Expose the network graph functionality in the webservice.

---

tools/hub-graph.hs

It only makes a few requests so doesn't need a token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/163)

fix: Allow unauthenticated requests in hub-graph.

---

src/GitHub/Tools/Changelogs.hs
tools/hub-changelog.hs
tools/hub-pulls.hs
tools/hub-roadmap.hs

Backlog is already at the end in the roadmap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/164)

fix: Don't put the newest milestone at the end.

---

src/GitHub/Types/Base/Permissions.hs
src/GitHub/Types/Base/Repository.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/166)

chore: Add new fields to github api.

---

github-tools.cabal
src/GitHub/WebHook/Handler.hs
stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/167)

chore: Upgrade stack LTS snapshot to 21.9 (GHC 9.4.6).

---

BUILD.bazel
src/GitHub/Types/Base/Repository.hs
web/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/169)

fix: Add new custom_properties field to Repository.

---

src/GitHub/Tools/AutoMerge.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/170)

chore: add myself to the trusted authors

---

BUILD.bazel
tools/BUILD.bazel
web/BUILD.bazel

This way we can do bazel build //... when cross-compiling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/172)

chore: Disable targets for cross-compilation.

---

admin/settings.yaml
src/GitHub/Tools/Settings.hs
tools/hub-settings.hs

- All common checks must be present in all repos.
- No checks may be duplicated in the list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/175)

feat: Add some settings validations.

---

admin/settings.yaml
src/GitHub/Paths/Repos/Labels.hs
src/GitHub/Tools/Requests.hs
src/GitHub/Tools/Settings.hs
src/GitHub/Types/Settings.hs

Also implemented sync.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/177)

feat: Add labels to settings.

---

src/GitHub/Tools/Settings.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/178)

cleanup: Minor cleanups in label sync code.

---

admin/settings.yaml
src/GitHub/Tools/Settings.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/181)

fix: Allow pushes to experimental without reviews.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/180)

chore: Add netlify to required checks on hs-toxcore.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/182)

fix: Correctly namespaced checks in hs-tokstyle.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/183)

chore: Make msvc builds in c-toxcore required checks.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/184)

chore: Add test/lint to zig-toxcore-c required checks.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/186)

chore: Add .github repo to the settings list.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/187)

chore: Remove windows from required checks in zig-toxcore-c.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/188)

chore: Add new haskell repos.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/189)

chore: Remove hound; add missing hs- repo checks.

---

admin/settings.yaml

It's not working anymore, and "draft PR" is a better alternative.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/191)

chore: Remove "WIP" status check.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/193)

chore: Add jvm-toxcore-c to managed settings file.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/196)

chore: Add buildifier and integration test to required toxic checks.

---

admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/195)

chore: Add additional checks for py-toxcore-c CI.

---

admin/settings.yaml

Restyled app is gone. We need to set up a CI workflow for it instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/197)

cleanup: Remove restyled task from required checks.

---

src/GitHub/Types/Base/CheckApp.hs
src/GitHub/Types/Base/Permissions.hs
src/GitHub/Types/Base/User.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/198)

feat: Support the latest github api updates.

---

src/GitHub/Types/Base/Permissions.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/199)

chore: Add more missing permissions

---

admin/settings.yaml
src/GitHub/Tools/Settings.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/200)

chore: Add buildifier and restyled to required checks.

---

.github/workflows/release.yml
admin/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/202)

chore: Add release-drafter github action.

---

github-tools.cabal
src/GitHub/Types/Workflow.hs
tools/BUILD.bazel
tools/check-workflows.hs

This allows us to enforce e.g. that every project has the common CI checks in its "ci.yml".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/203)

feat: Add tool to check workflows against a base yaml file.

---

.restyled.yaml
tools/hub-restyled

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/204)

feat: Add tool to download and apply a patch from restyled.

---

admin/BUILD.bazel
admin/settings.yaml
admin/settings_test.pl

Also added some dependabot PR labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/205)

test: Check that all toktok-stack modules are in settings.yaml.

---

web/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/208)

fix: Stop crashing the web service on render.com.

---

admin/repos.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/209)

chore: Add tokhub, remove c-toxcore-hs.

---

admin/repos.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/211)

chore: Add new qTox CI checks to list of required checks.

---

admin/repos.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/213)

chore: Add cyclone repo config.

---

.github/docker/server.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/216)

chore: Add back the dockerfile needed for render.com.

---

.github/workflows/draft.yml
.reviewable/completion.js
.reviewable/settings.yaml
admin/org.yaml
admin/repos.yaml
github-tools.cabal
src/GitHub/Types/IssueTemplate.hs
src/GitHub/Types/Json.hs
src/GitHub/Types/Workflow.hs
tools/check-workflows.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/217)

feat: Add issue template validation support.

---

src/GitHub/Tools/AutoMerge.hs

I don't see why automerge isn't working. Hopefully this will give me some insights.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/219)

cleanup: Add more logging.

---

admin/org.yaml

Also add Tobi to reviewers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/221)

chore: Reduce spam on some members.

---

github-tools.cabal
tools/hub-automerge.hs
web/webservice.hs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/220)

fix: Use `-threaded` for webservice so it crashes less.

---

.cirrus.yml
github-tools.cabal

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/224)

chore: Update bounds of github module version.

---

.cirrus.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/225)

chore: Re-enable cirrus CI.
