.gitignore, Makefile, github-tools.cabal, src/Review.hs, src/changelog.hs
- Generates a change log for closed milestones.
- Groups by issues/prs.
- Displays only merged PRs, not all closed PRs.
- Shows only issues/prs that have a milestone assigned (should be all).
Future plans: add support for special labels to exclude things from the changelog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/8)
=> Finish implementing the changelog generator.

github-tools.cabal, src/Requests.hs, src/changelog.hs, src/pull-status.hs
It is still mandatory in pull-status, because that makes too many
requests. The changelog generator only makes two requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/10)
=> Make authentication optional in changelog generator.

Procfile, github-tools.cabal, src/Changelogs.hs, src/PullStatus.hs, src/Requests.hs, tools/changelog.hs, tools/pull-status.hs, tools/webservice.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/11)
=> Add simple hello world webservice.

github-tools.cabal, web/GitHub/Types.hs, web/GitHub/Types/Base.hs, web/GitHub/Types/Events.hs, web/GitHub/WebHook/Handler.hs, web/TokTok/Webhooks.hs
We're going to extend and maintain this ourselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/13)
=> Import github webhook code.

web/GitHub/Types/Base.hs, web/GitHub/Types/Events.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/14)
=> Add support for commit_comment event.

github-tools.cabal, web/GitHub/Types/Base.hs, web/GitHub/Types/Events.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/15)
=> Support more events.

web/GitHub/Types/Base/PullRequest.hs
GitHub recently added this field. They even
[documented](https://developer.github.com/v3/pulls/#get-a-single-pull-request)
it. I have no idea how to get updates on these changes though. I found it
because git-critique is very strict in accepting webhooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/42)
=> Add `maintainer_can_modify` field to pull request.

.travis.yml, templates/base.yml, templates/haskell.yml, tools/expand-yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/45)
=> Erase template fields

.travis.yml, templates/base.yml
This was a bad idea. It prevents us from restarting past builds, because
Travis will always only check out master, not actually the ref that was
built.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/54)
=> Don't use `git.depth=1` anymore.

reviewable_script.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/55)
=> Rename references of admin_approved to adminApproved in reviewable.js.

github-tools.cabal, web/TokTok/Hello.hs
This way, the pulls page can be up to date without us hammering the
GitHub API for every request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/57)
=> Cache pull request info for 30 seconds instead of forever.

src/Changelogs.hs
It used to bring v0.3.0 to the front, before Backlog and all others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/72)
=> Fix roadmap milestone ordering.

src/GitHub/Types/Base/Organization.hs, src/GitHub/Types/Base/PullRequest.hs, src/GitHub/Types/Base/User.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/78)
=> Add email to Organization type.

.travis.yml, github-tools.cabal, src/PullStatus.hs, templates/haskell.yml
Needs https://github.com/phadej/github/pull/311.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/86)
=>  Add "behind" mergeable state.

BUILD.bazel, appveyor.yml, src/GitHub/Types/Base/Commit.hs, src/GitHub/Types/Base/DeploymentPayload.hs, src/GitHub/Types/Base/PullRequest.hs, test/GitHub/Types/BaseSpec.hs, test/GitHub/Types/EventsSpec.hs
And also some other updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/github-tools/95)
=> PullRequest.head.repo can be null.

tools/git-co, tools/git-d, tools/git-s, tools/git-ss, tools/git-stack-status, tools/git-submit
All new git-* tools should live in the github-tools repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/105)
=> Move git tools from toktok-stack.

.travis.yml, src/GitHub/Types/Base/SimplePullRequest.hs
This is the version of "pull_request" that we get in
"pull_request_review" events. The complete PullRequest is only received
in "pull_request" events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/110)
=> Add some missing fields to SimplePullRequest.

.travis.yml, BUILD.bazel, github-tools.cabal, test/GitHub/Types/BaseSpec.hs, test/GitHub/Types/EventsSpec.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/114)
=> Upload hackage releases from Travis on tags.

BUILD.bazel, github-tools.cabal, test/GitHub/Types/BaseSpec.hs, test/GitHub/Types/EventsSpec.hs
It was 100, and took several minutes to complete. With 10, it takes 0.2
seconds, with 20, it takes 4.5 seconds. This is a reasonable tradeoff
between time spent running the test and its exhaustiveness. Most of the
time we find the errors within the first 10 tests anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/113)
=> Reduce number of testcases for property tests to 20.

tools/git-submit, tools/git-sync
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/116)
=> Teach "git submit" the same user:branch trick as "git sync".

BUILD.bazel
This is becoming the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/118)
=> Remove standard_travis setting in BUILD.bazel.

.github/settings.yml, .github/workflows/checks.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, BUILD.bazel, stack.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/126)
=> chore: Fix stack build; add github workflows to ensure it stays fixed.

.cirrus.yml, .github/settings.yml, .github/workflows/publish.yml, BUILD.bazel, tools/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/128)
=> feat: Make git-submit work without argument.

BUILD.bazel, README.md, github-tools.cabal, src/Changelogs.hs, tools/BUILD.bazel, tools/hub-changelog.hs, tools/hub-roadmap.hs
Fixes #80.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/131)
=> fix: Sort milestone versions correctly in changelog/roadmap.

.github/docker/Dockerfile, tools/hub-pulls.hs, web/TokTok/Hello.hs, web/TokTok/Webhooks.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/134)
=> chore: Remove unused imports.

BUILD.bazel, src/GitHub/Types/Base/Permissions.hs
These things are sometimes set, sometimes not, so it's kind of random
whether github actually sends all perms or some random subset.
Eventually we might get all of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/137)
=> chore: Add yet another missing perm.

.github/docker/Dockerfile.heroku, BUILD.bazel, github-tools.cabal, src/GitHub/Tools/Changelogs.hs, src/GitHub/Tools/PullRequestInfo.hs, src/GitHub/Tools/PullStatus.hs, src/GitHub/Tools/Requests.hs, tools/BUILD.bazel, tools/hub-changelog.hs, tools/hub-pulls.hs, tools/hub-roadmap.hs, web/BUILD.bazel, web/TokTok/Hello.hs
Also renamed some files and split the bazel build so we don't rebuild
everything all the time. This speeds up development of tools when we're
not modifying the base or events types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/139)
=> chore: Install ca-certificates on heroku.

.github/docker/Dockerfile, .github/docker/Dockerfile.heroku
This greatly speeds up the heroku build following the docker image
build, because it doesn't need to download the haskell compiler etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/140)
=> chore: Upload only installed binaries into the docker image.

src/GitHub/Tools/AutoMerge.hs, src/GitHub/Tools/PullStatus.hs, tools/hub-automerge.hs, web/TokTok/Handlers.hs
We were checking *all* PRs of all repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/143)
=> perf: Only check the repo the check_suite event was for.

src/GitHub/Tools/AutoMerge.hs, src/GitHub/Tools/PullStatus.hs, tools/hub-automerge.hs, web/TokTok/Handlers.hs, web/webservice.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/144)
=> perf: Some more optimisations: make fewer calls to GH API.

src/GitHub/Tools/AutoMerge.hs, tools/hub-automerge.hs, web/TokTok/Handlers.hs, web/TokTok/Webhooks.hs
This is the full name, not the username, and thus completely useless.
In exchange, we wait 30 seconds to avoid running out of quota.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/150)
=> fix: Don't check author in the `check_suite` message.

github-tools.cabal
aeson 2 introduced incompatible changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/151)
=> chore: Limit aeson version compatibility.

.github/workflows/ci.yml, src/GitHub/Types/Base/Commit.hs
Ridiculous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/153)
=> fix: Sometimes the commit user isn't set in check_suite events.

BUILD.bazel, github-tools.cabal, src/GitHub/Tools/AutoMerge.hs, src/GitHub/Tools/NetworkGraph.hs, src/GitHub/Types/Base/Release.hs, src/GitHub/Types/Events/ReleaseEvent.hs, tools/hub-graph.hs
Fixes https://github.com/TokTok/hs-github-tools/issues/76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/160)
=> feat: Add github network graph tool.

src/GitHub/Tools/AutoMerge.hs, src/GitHub/Tools/PullStatus.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-github-tools/165)
=> fix: Make automerge work when fork repo name != base repo name.

BUILD.bazel, github-tools.cabal
Needed for vscode and haskell-language-server to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/171)
=> chore: Make haskell code visible to ghci.

admin/settings.yaml
It's broken. I'll fix it later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/192)
=> chore: Remove codeql from toktok-stack for now.

admin/settings.yaml, src/GitHub/WebHook/Handler.hs
The jvm-toxcore-c ones were renamed a while back.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/201)
=> chore: Clean up jvm-toxcore-c CI checks.

admin/settings.yaml
Also only allow rebase merge. Not that it does anything because we can't automerge anyway, but it signals how we want to merge things (not necessarily squashing everything into 1 commit if it makes sense to have multiple).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/206)
=> chore: Make qtox CI checks mandatory.

admin/BUILD.bazel, admin/push, admin/repos.yaml, admin/repos_test.pl, src/GitHub/Paths/Repos/Rulesets.hs, src/GitHub/Tools/Settings.hs, src/GitHub/Types/Settings.hs
These allow us to block branch creation in the upstream. This could be accidental where a repo maintainer pushes to `TokTok/$repo` instead of their fork.
This is in addition to branch protection rules that apply only to `master`. No branch protection is applied to other branches, but only 2 bots are currently allowed to create branches other than `master`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/207)
=> feat: Add support for GitHub rulesets.

admin/repos.yaml
We're switching to a normal jvm build there for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/210)
=> chore: Remove the native kmp build from jvm-toxcore-c

admin/repos.yaml, src/GitHub/Tools/AutoMerge.hs
prUser is actually the owner of the branch, not the committer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-github-tools/222)
=> fix: Trust "TokTok" as a branch origin.
